class Datasets:
    POINTS_SYNTHETIC = "Random points"
    POINTS_FLOWER = "Circular points"
    POINTS_REUTERS = "Reuters"
    POINTS_CLOUD = "Points cloud"
    LINES_SYNTHETIC = "Synthetic lines"
    LINES_COVTYPE = "Covtype"
    LINES_KDDCUP = "KDD Cup 99"
    #LINES_TRIANGULATION = "Lines: Triangulation"    
    DATASETS_POINTS = (POINTS_SYNTHETIC, POINTS_FLOWER, POINTS_REUTERS, POINTS_CLOUD) 
    DATASETS_LINES = (LINES_SYNTHETIC, LINES_COVTYPE, LINES_KDDCUP)   
    DATASETS_ALL = DATASETS_POINTS + DATASETS_LINES    
